sudo: false
language: python
python: 3.6

# tell travis to cache ~/.cache/pip
cache: pip

env:
  - TOX_ENV=packaging
  - TOX_ENV=pep8
  - TOX_ENV=py27

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
