[tool.towncrier]
    package = "synapse"
    filename = "CHANGES.md"
    directory = "changelog.d"
    issue_format = "[\\#{issue}](https://github.com/matrix-org/synapse/issues/{issue})"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "docker"
        name = "Updates to the Docker image"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Internal Changes"
        showcontent = true

[tool.black]
target-version = ['py36']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.tox
    | \.venv
    | \.env
    | env
    | _build
    | _trial_temp.*
    | build
    | dist
    | debian
  )/
)
'''

[tool.mypy]
namespace_packages = true
plugins = [
    "mypy_zope:plugin",
    "scripts-dev/mypy_synapse_plugin.py",
]
follow_imports = "normal"
check_untyped_defs = true
show_error_codes = true
show_traceback = true
mypy_path = "stubs"
warn_unreachable = true
local_partial_types = true
no_implicit_optional = true

files = [
    "scripts-dev/sign_json",
    "setup.py",
    "synapse/",
    "tests/",
]

# Note: Better exclusion syntax coming in mypy > 0.910
# https://github.com/python/mypy/pull/11329
#
# For now, set the (?x) flag enable "verbose" regexes
# https://docs.python.org/3/library/re.html#re.X

exclude = """(?x)
    ^(
     |synapse/storage/databases/__init__.py
     |synapse/storage/databases/main/__init__.py
     |synapse/storage/databases/main/account_data.py
     |synapse/storage/databases/main/cache.py
     |synapse/storage/databases/main/censor_events.py
     |synapse/storage/databases/main/deviceinbox.py
     |synapse/storage/databases/main/devices.py
     |synapse/storage/databases/main/directory.py
     |synapse/storage/databases/main/e2e_room_keys.py
     |synapse/storage/databases/main/end_to_end_keys.py
     |synapse/storage/databases/main/event_federation.py
     |synapse/storage/databases/main/event_push_actions.py
     |synapse/storage/databases/main/events_bg_updates.py
     |synapse/storage/databases/main/events_forward_extremities.py
     |synapse/storage/databases/main/events_worker.py
     |synapse/storage/databases/main/filtering.py
     |synapse/storage/databases/main/group_server.py
     |synapse/storage/databases/main/lock.py
     |synapse/storage/databases/main/media_repository.py
     |synapse/storage/databases/main/metrics.py
     |synapse/storage/databases/main/monthly_active_users.py
     |synapse/storage/databases/main/openid.py
     |synapse/storage/databases/main/presence.py
     |synapse/storage/databases/main/profile.py
     |synapse/storage/databases/main/purge_events.py
     |synapse/storage/databases/main/push_rule.py
     |synapse/storage/databases/main/receipts.py
     |synapse/storage/databases/main/rejections.py
     |synapse/storage/databases/main/room.py
     |synapse/storage/databases/main/room_batch.py
     |synapse/storage/databases/main/roommember.py
     |synapse/storage/databases/main/search.py
     |synapse/storage/databases/main/signatures.py
     |synapse/storage/databases/main/state.py
     |synapse/storage/databases/main/state_deltas.py
     |synapse/storage/databases/main/stats.py
     |synapse/storage/databases/main/tags.py
     |synapse/storage/databases/main/transactions.py
     |synapse/storage/databases/main/user_directory.py
     |synapse/storage/databases/main/user_erasure_store.py
     |synapse/storage/schema/

     |tests/api/test_auth.py
     |tests/api/test_ratelimiting.py
     |tests/app/test_openid_listener.py
     |tests/appservice/test_scheduler.py
     |tests/config/test_cache.py
     |tests/config/test_tls.py
     |tests/crypto/test_keyring.py
     |tests/events/test_presence_router.py
     |tests/events/test_utils.py
     |tests/federation/test_federation_catch_up.py
     |tests/federation/test_federation_sender.py
     |tests/federation/test_federation_server.py
     |tests/federation/transport/test_knocking.py
     |tests/federation/transport/test_server.py
     |tests/handlers/test_cas.py
     |tests/handlers/test_directory.py
     |tests/handlers/test_e2e_keys.py
     |tests/handlers/test_federation.py
     |tests/handlers/test_oidc.py
     |tests/handlers/test_presence.py
     |tests/handlers/test_profile.py
     |tests/handlers/test_saml.py
     |tests/handlers/test_typing.py
     |tests/http/federation/test_matrix_federation_agent.py
     |tests/http/federation/test_srv_resolver.py
     |tests/http/test_fedclient.py
     |tests/http/test_proxyagent.py
     |tests/http/test_servlet.py
     |tests/http/test_site.py
     |tests/logging/__init__.py
     |tests/logging/test_terse_json.py
     |tests/module_api/test_api.py
     |tests/push/test_email.py
     |tests/push/test_http.py
     |tests/push/test_presentable_names.py
     |tests/push/test_push_rule_evaluator.py
     |tests/rest/admin/test_admin.py
     |tests/rest/admin/test_device.py
     |tests/rest/admin/test_media.py
     |tests/rest/admin/test_server_notice.py
     |tests/rest/admin/test_user.py
     |tests/rest/admin/test_username_available.py
     |tests/rest/client/test_account.py
     |tests/rest/client/test_events.py
     |tests/rest/client/test_filter.py
     |tests/rest/client/test_groups.py
     |tests/rest/client/test_register.py
     |tests/rest/client/test_report_event.py
     |tests/rest/client/test_rooms.py
     |tests/rest/client/test_third_party_rules.py
     |tests/rest/client/test_transactions.py
     |tests/rest/client/test_typing.py
     |tests/rest/client/utils.py
     |tests/rest/key/v2/test_remote_key_resource.py
     |tests/rest/media/v1/test_base.py
     |tests/rest/media/v1/test_media_storage.py
     |tests/rest/media/v1/test_url_preview.py
     |tests/scripts/test_new_matrix_user.py
     |tests/server.py
     |tests/server_notices/test_resource_limits_server_notices.py
     |tests/state/test_v2.py
     |tests/storage/test_account_data.py
     |tests/storage/test_appservice.py
     |tests/storage/test_background_update.py
     |tests/storage/test_base.py
     |tests/storage/test_client_ips.py
     |tests/storage/test_database.py
     |tests/storage/test_event_federation.py
     |tests/storage/test_id_generators.py
     |tests/storage/test_roommember.py
     |tests/test_metrics.py
     |tests/test_phone_home.py
     |tests/test_server.py
     |tests/test_state.py
     |tests/test_terms_auth.py
     |tests/test_visibility.py
     |tests/unittest.py
     |tests/util/caches/test_cached_call.py
     |tests/util/caches/test_deferred_cache.py
     |tests/util/caches/test_descriptors.py
     |tests/util/caches/test_response_cache.py
     |tests/util/caches/test_ttlcache.py
     |tests/util/test_async_helpers.py
     |tests/util/test_batching_queue.py
     |tests/util/test_dict_cache.py
     |tests/util/test_expiring_cache.py
     |tests/util/test_file_consumer.py
     |tests/util/test_linearizer.py
     |tests/util/test_logcontext.py
     |tests/util/test_lrucache.py
     |tests/util/test_rwlock.py
     |tests/util/test_wheel_timer.py
     |tests/utils.py
     )$
"""

[[tool.mypy.overrides]]
module = [
    "synapse.api.*",
    "synapse.app.*",
    "synapse.crypto.*",
    "synapse.events.*",
    "synapse.handlers.*",
    "synapse.push.*",
    "synapse.rest.*",
    "synapse.server_notices.*",
    "synapse.state.*",
    "synapse.storage.databases.main.client_ips",
    "synapse.storage.util.*",
    "synapse.streams.*",
    "synapse.util.batching_queue",
    "synapse.util.caches.cached_call",
    "synapse.util.caches.dictionary_cache",
    "synapse.util.caches.lrucache",
    "synapse.util.caches.response_cache",
    "synapse.util.caches.stream_change_cache",
    "synapse.util.caches.ttl_cache",
    "synapse.util.daemonize",
    "synapse.util.file_consumer",
    "synapse.util.frozenutils",
    "synapse.util.hash",
    "synapse.util.httpresourcetree",
    "synapse.util.iterutils",
    "synapse.util.linked_list",
    "synapse.util.logcontext",
    "synapse.util.logformatter",
    "synapse.util.macaroons",
    "synapse.util.manhole",
    "synapse.util.module_loader",
    "synapse.util.msisdn",
    "synapse.util.patch_inline_callbacks",
    "synapse.util.ratelimitutils",
    "synapse.util.retryutils",
    "synapse.util.rlimit",
    "synapse.util.stringutils",
    "synapse.util.templates",
    "synapse.util.threepids",
    "synapse.util.versionstring",
    "synapse.util.wheel_timer",
    "tests.handlers.test_user_directory",
    "tests.storage.test_user_directory",
]
disallow_untyped_defs = true

# Dependencies without annotations
# Before ignoring a module, check to see if type stubs are available.
# The `typeshed` project maintains stubs here:
#     https://github.com/python/typeshed/tree/master/stubs
# and for each package `foo` there's a corresponding `types-foo` package on PyPI,
# which we can pull in as a dev dependency by adding to `setup.py`'s
# `CONDITIONAL_REQUIREMENTS["mypy"]` list.
[[tool.mypy.overrides]]
module = [
    "authlib.*",
    "bcrypt",
    "canonicaljson",
    "constantly",
    "daemonize",
    "h11",
    "hiredis",
    "hyperlink",
    "ijson.*",
    "jaeger_client.*",
    "josepy.*",
    "jwt.*",
    "lxml",
    "msgpack",
    "nacl.*",
    "netaddr",
    "opentracing",
    "parameterized.*",
    "phonenumbers.*",
    "prometheus_client.*",
    "pymacaroons.*",
    "pympler.*",
    "rust_python_jaeger_reporter.*",
    "saml2.*",
    "sentry_sdk",
    "service_identity.*",
    "signedjson.*",
    "treq.*",
    "twisted.*",
    "zope",
]
ignore_missing_imports = true
