[tool.towncrier]
    package = "synapse"
    filename = "CHANGES.md"
    directory = "changelog.d"
    issue_format = "[\\#{issue}](https://github.com/matrix-org/synapse/issues/{issue})"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "docker"
        name = "Updates to the Docker image"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Internal Changes"
        showcontent = true

[tool.black]
target-version = ['py36']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.tox
    | \.venv
    | \.env
    | env
    | _build
    | _trial_temp.*
    | build
    | dist
    | debian
  )/
)
'''

[tool.mypy]
namespace_packages = true
plugins = [
    "mypy_zope:plugin",
    "scripts-dev/mypy_synapse_plugin.py",
]
follow_imports = "normal"
check_untyped_defs = true
show_error_codes = true
show_traceback = true
mypy_path = "stubs"
warn_unreachable = true
local_partial_types = true
no_implicit_optional = true
disallow_untyped_defs = true

files = [
    "scripts-dev/sign_json",
    "setup.py",
    "synapse/",
    "tests/",
]

# Note: Better exclusion syntax coming in mypy > 0.910
# https://github.com/python/mypy/pull/11329
#
# For now, set the (?x) flag enable "verbose" regexes
# https://docs.python.org/3/library/re.html#re.X

exclude = """(?x)
    ^(
     |synapse/storage/databases/__init__.py
     |synapse/storage/databases/main/__init__.py
     |synapse/storage/databases/main/account_data.py
     |synapse/storage/databases/main/cache.py
     |synapse/storage/databases/main/censor_events.py
     |synapse/storage/databases/main/deviceinbox.py
     |synapse/storage/databases/main/devices.py
     |synapse/storage/databases/main/directory.py
     |synapse/storage/databases/main/e2e_room_keys.py
     |synapse/storage/databases/main/end_to_end_keys.py
     |synapse/storage/databases/main/event_federation.py
     |synapse/storage/databases/main/event_push_actions.py
     |synapse/storage/databases/main/events_bg_updates.py
     |synapse/storage/databases/main/events_forward_extremities.py
     |synapse/storage/databases/main/events_worker.py
     |synapse/storage/databases/main/filtering.py
     |synapse/storage/databases/main/group_server.py
     |synapse/storage/databases/main/lock.py
     |synapse/storage/databases/main/media_repository.py
     |synapse/storage/databases/main/metrics.py
     |synapse/storage/databases/main/monthly_active_users.py
     |synapse/storage/databases/main/openid.py
     |synapse/storage/databases/main/presence.py
     |synapse/storage/databases/main/profile.py
     |synapse/storage/databases/main/purge_events.py
     |synapse/storage/databases/main/push_rule.py
     |synapse/storage/databases/main/receipts.py
     |synapse/storage/databases/main/rejections.py
     |synapse/storage/databases/main/room.py
     |synapse/storage/databases/main/room_batch.py
     |synapse/storage/databases/main/roommember.py
     |synapse/storage/databases/main/search.py
     |synapse/storage/databases/main/signatures.py
     |synapse/storage/databases/main/state.py
     |synapse/storage/databases/main/state_deltas.py
     |synapse/storage/databases/main/stats.py
     |synapse/storage/databases/main/tags.py
     |synapse/storage/databases/main/transactions.py
     |synapse/storage/databases/main/user_directory.py
     |synapse/storage/databases/main/user_erasure_store.py
     |synapse/storage/schema/

     |tests/api/test_auth.py
     |tests/api/test_ratelimiting.py
     |tests/app/test_openid_listener.py
     |tests/appservice/test_scheduler.py
     |tests/config/test_cache.py
     |tests/config/test_tls.py
     |tests/crypto/test_keyring.py
     |tests/events/test_presence_router.py
     |tests/events/test_utils.py
     |tests/federation/test_federation_catch_up.py
     |tests/federation/test_federation_sender.py
     |tests/federation/test_federation_server.py
     |tests/federation/transport/test_knocking.py
     |tests/federation/transport/test_server.py
     |tests/handlers/test_cas.py
     |tests/handlers/test_directory.py
     |tests/handlers/test_e2e_keys.py
     |tests/handlers/test_federation.py
     |tests/handlers/test_oidc.py
     |tests/handlers/test_presence.py
     |tests/handlers/test_profile.py
     |tests/handlers/test_saml.py
     |tests/handlers/test_typing.py
     |tests/http/federation/test_matrix_federation_agent.py
     |tests/http/federation/test_srv_resolver.py
     |tests/http/test_fedclient.py
     |tests/http/test_proxyagent.py
     |tests/http/test_servlet.py
     |tests/http/test_site.py
     |tests/logging/__init__.py
     |tests/logging/test_terse_json.py
     |tests/module_api/test_api.py
     |tests/push/test_email.py
     |tests/push/test_http.py
     |tests/push/test_presentable_names.py
     |tests/push/test_push_rule_evaluator.py
     |tests/rest/admin/test_admin.py
     |tests/rest/admin/test_device.py
     |tests/rest/admin/test_media.py
     |tests/rest/admin/test_server_notice.py
     |tests/rest/admin/test_user.py
     |tests/rest/admin/test_username_available.py
     |tests/rest/client/test_account.py
     |tests/rest/client/test_events.py
     |tests/rest/client/test_filter.py
     |tests/rest/client/test_groups.py
     |tests/rest/client/test_register.py
     |tests/rest/client/test_report_event.py
     |tests/rest/client/test_rooms.py
     |tests/rest/client/test_third_party_rules.py
     |tests/rest/client/test_transactions.py
     |tests/rest/client/test_typing.py
     |tests/rest/client/utils.py
     |tests/rest/key/v2/test_remote_key_resource.py
     |tests/rest/media/v1/test_base.py
     |tests/rest/media/v1/test_media_storage.py
     |tests/rest/media/v1/test_url_preview.py
     |tests/scripts/test_new_matrix_user.py
     |tests/server.py
     |tests/server_notices/test_resource_limits_server_notices.py
     |tests/state/test_v2.py
     |tests/storage/test_account_data.py
     |tests/storage/test_appservice.py
     |tests/storage/test_background_update.py
     |tests/storage/test_base.py
     |tests/storage/test_client_ips.py
     |tests/storage/test_database.py
     |tests/storage/test_event_federation.py
     |tests/storage/test_id_generators.py
     |tests/storage/test_roommember.py
     |tests/test_metrics.py
     |tests/test_phone_home.py
     |tests/test_server.py
     |tests/test_state.py
     |tests/test_terms_auth.py
     |tests/test_visibility.py
     |tests/unittest.py
     |tests/util/caches/test_cached_call.py
     |tests/util/caches/test_deferred_cache.py
     |tests/util/caches/test_descriptors.py
     |tests/util/caches/test_response_cache.py
     |tests/util/caches/test_ttlcache.py
     |tests/util/test_async_helpers.py
     |tests/util/test_batching_queue.py
     |tests/util/test_dict_cache.py
     |tests/util/test_expiring_cache.py
     |tests/util/test_file_consumer.py
     |tests/util/test_linearizer.py
     |tests/util/test_logcontext.py
     |tests/util/test_lrucache.py
     |tests/util/test_rwlock.py
     |tests/util/test_wheel_timer.py
     |tests/utils.py
     )$
"""

[[tool.mypy.overrides]]
module = [
    "synapse._scripts.register_new_matrix_user",
    "synapse.appservice",
    "synapse.appservice.api",
    "synapse.appservice.scheduler",
    "synapse.config.__main__",
    "synapse.config._base",
    "synapse.config.account_validity",
    "synapse.config.api",
    "synapse.config.appservice",
    "synapse.config.auth",
    "synapse.config.cache",
    "synapse.config.captcha",
    "synapse.config.cas",
    "synapse.config.consent",
    "synapse.config.database",
    "synapse.config.emailconfig",
    "synapse.config.experimental",
    "synapse.config.federation",
    "synapse.config.groups",
    "synapse.config.jwt",
    "synapse.config.key",
    "synapse.config.logger",
    "synapse.config.metrics",
    "synapse.config.modules",
    "synapse.config.oembed",
    "synapse.config.oidc",
    "synapse.config.password_auth_providers",
    "synapse.config.push",
    "synapse.config.ratelimiting",
    "synapse.config.redis",
    "synapse.config.registration",
    "synapse.config.repository",
    "synapse.config.retention",
    "synapse.config.room",
    "synapse.config.room_directory",
    "synapse.config.saml2",
    "synapse.config.server",
    "synapse.config.server_notices",
    "synapse.config.spam_checker",
    "synapse.config.sso",
    "synapse.config.stats",
    "synapse.config.third_party_event_rules",
    "synapse.config.tls",
    "synapse.config.tracer",
    "synapse.config.user_directory",
    "synapse.config.voip",
    "synapse.config.workers",
    "synapse.event_auth",
    "synapse.federation.federation_client",
    "synapse.federation.federation_server",
    "synapse.federation.persistence",
    "synapse.federation.send_queue",
    "synapse.federation.sender.per_destination_queue",
    "synapse.federation.transport.client",
    "synapse.federation.transport.server",
    "synapse.federation.transport.server._base",
    "synapse.groups.groups_server",
    "synapse.http",
    "synapse.http.additional_resource",
    "synapse.http.client",
    "synapse.http.connectproxyclient",
    "synapse.http.federation.matrix_federation_agent",
    "synapse.http.federation.srv_resolver",
    "synapse.http.federation.well_known_resolver",
    "synapse.http.matrixfederationclient",
    "synapse.http.proxyagent",
    "synapse.http.request_metrics",
    "synapse.http.server",
    "synapse.http.servlet",
    "synapse.http.site",
    "synapse.logging._remote",
    "synapse.logging.context",
    "synapse.logging.formatter",
    "synapse.logging.handlers",
    "synapse.logging.opentracing",
    "synapse.logging.scopecontextmanager",
    "synapse.logging.utils",
    "synapse.metrics",
    "synapse.metrics._exposition",
    "synapse.metrics.background_process_metrics",
    "synapse.metrics.jemalloc",
    "synapse.module_api",
    "synapse.notifier",
    "synapse.python_dependencies",
    "synapse.replication.http",
    "synapse.replication.http._base",
    "synapse.replication.http.account_data",
    "synapse.replication.http.devices",
    "synapse.replication.http.federation",
    "synapse.replication.http.login",
    "synapse.replication.http.membership",
    "synapse.replication.http.presence",
    "synapse.replication.http.push",
    "synapse.replication.http.register",
    "synapse.replication.http.send_event",
    "synapse.replication.http.streams",
    "synapse.replication.slave.storage._base",
    "synapse.replication.slave.storage._slaved_id_tracker",
    "synapse.replication.slave.storage.client_ips",
    "synapse.replication.slave.storage.devices",
    "synapse.replication.slave.storage.events",
    "synapse.replication.slave.storage.filtering",
    "synapse.replication.slave.storage.groups",
    "synapse.replication.slave.storage.push_rule",
    "synapse.replication.slave.storage.pushers",
    "synapse.replication.tcp.client",
    "synapse.replication.tcp.commands",
    "synapse.replication.tcp.handler",
    "synapse.replication.tcp.protocol",
    "synapse.replication.tcp.redis",
    "synapse.replication.tcp.resource",
    "synapse.replication.tcp.streams._base",
    "synapse.replication.tcp.streams.events",
    "synapse.server",
    "synapse.storage.background_updates",
    "synapse.storage.database",
    "synapse.storage.databases.main.appservice",
    "synapse.storage.databases.main.events",
    "synapse.storage.databases.main.keys",
    "synapse.storage.databases.main.pusher",
    "synapse.storage.databases.main.registration",
    "synapse.storage.databases.main.relations",
    "synapse.storage.databases.main.stream",
    "synapse.storage.databases.main.ui_auth",
    "synapse.storage.engines",
    "synapse.storage.engines._base",
    "synapse.storage.engines.postgres",
    "synapse.storage.engines.sqlite",
    "synapse.storage.persist_events",
    "synapse.storage.prepare_database",
    "synapse.storage.state",
    "synapse.storage.types",
    "synapse.types",
    "synapse.util",
    "synapse.util.async_helpers",
    "synapse.util.caches",
    "synapse.util.caches.deferred_cache",
    "synapse.util.caches.descriptors",
    "synapse.util.caches.expiringcache",
    "synapse.util.caches.treecache",
    "synapse.util.distributor",
    "synapse.util.gai_resolver",
    "synapse.util.metrics",
    "synapse.visibility",
    "tests.api.test_filtering",
    "tests.app.test_phone_stats_home",
    "tests.appservice.test_appservice",
    "tests.config.test___main__",
    "tests.config.test_base",
    "tests.config.test_database",
    "tests.config.test_generate",
    "tests.config.test_load",
    "tests.config.test_ratelimiting",
    "tests.config.test_room_directory",
    "tests.config.test_server",
    "tests.config.test_util",
    "tests.config.utils",
    "tests.crypto.test_event_signing",
    "tests.events.test_snapshot",
    "tests.federation.test_complexity",
    "tests.handlers.test_admin",
    "tests.handlers.test_appservice",
    "tests.handlers.test_auth",
    "tests.handlers.test_device",
    "tests.handlers.test_e2e_room_keys",
    "tests.handlers.test_message",
    "tests.handlers.test_password_providers",
    "tests.handlers.test_receipts",
    "tests.handlers.test_register",
    "tests.handlers.test_room",
    "tests.handlers.test_room_summary",
    "tests.handlers.test_send_email",
    "tests.handlers.test_stats",
    "tests.handlers.test_sync",
    "tests.http",
    "tests.http.test_additional_resource",
    "tests.http.test_client",
    "tests.http.test_endpoint",
    "tests.http.test_simple_client",
    "tests.logging.test_remote_handler",
    "tests.replication._base",
    "tests.replication.slave.storage._base",
    "tests.replication.slave.storage.test_account_data",
    "tests.replication.slave.storage.test_events",
    "tests.replication.slave.storage.test_receipts",
    "tests.replication.tcp.streams.test_account_data",
    "tests.replication.tcp.streams.test_events",
    "tests.replication.tcp.streams.test_federation",
    "tests.replication.tcp.streams.test_typing",
    "tests.replication.tcp.test_commands",
    "tests.replication.tcp.test_remote_server_up",
    "tests.replication.test_auth",
    "tests.replication.test_client_reader_shard",
    "tests.replication.test_federation_ack",
    "tests.replication.test_federation_sender_shard",
    "tests.replication.test_multi_media_repo",
    "tests.replication.test_pusher_shard",
    "tests.replication.test_sharded_event_persister",
    "tests.rest.admin.test_background_updates",
    "tests.rest.admin.test_event_reports",
    "tests.rest.admin.test_registration_tokens",
    "tests.rest.admin.test_room",
    "tests.rest.admin.test_statistics",
    "tests.rest.client.test_auth",
    "tests.rest.client.test_capabilities",
    "tests.rest.client.test_consent",
    "tests.rest.client.test_directory",
    "tests.rest.client.test_ephemeral_message",
    "tests.rest.client.test_identity",
    "tests.rest.client.test_keys",
    "tests.rest.client.test_login",
    "tests.rest.client.test_password_policy",
    "tests.rest.client.test_power_levels",
    "tests.rest.client.test_presence",
    "tests.rest.client.test_profile",
    "tests.rest.client.test_push_rule_attrs",
    "tests.rest.client.test_redactions",
    "tests.rest.client.test_relations",
    "tests.rest.client.test_retention",
    "tests.rest.client.test_sendtodevice",
    "tests.rest.client.test_shadow_banned",
    "tests.rest.client.test_shared_rooms",
    "tests.rest.client.test_sync",
    "tests.rest.client.test_upgrade_room",
    "tests.rest.media.v1.test_filepath",
    "tests.rest.media.v1.test_oembed",
    "tests.rest.test_health",
    "tests.rest.test_well_known",
    "tests.server_notices.test_consent",
    "tests.storage.databases.main.test_deviceinbox",
    "tests.storage.databases.main.test_events_worker",
    "tests.storage.databases.main.test_lock",
    "tests.storage.databases.main.test_room",
    "tests.storage.test__base",
    "tests.storage.test_cleanup_extrems",
    "tests.storage.test_devices",
    "tests.storage.test_directory",
    "tests.storage.test_e2e_room_keys",
    "tests.storage.test_end_to_end_keys",
    "tests.storage.test_event_chain",
    "tests.storage.test_event_metrics",
    "tests.storage.test_event_push_actions",
    "tests.storage.test_events",
    "tests.storage.test_keys",
    "tests.storage.test_main",
    "tests.storage.test_monthly_active_users",
    "tests.storage.test_profile",
    "tests.storage.test_purge",
    "tests.storage.test_redaction",
    "tests.storage.test_registration",
    "tests.storage.test_rollback_worker",
    "tests.storage.test_room",
    "tests.storage.test_room_search",
    "tests.storage.test_state",
    "tests.storage.test_stream",
    "tests.storage.test_transactions",
    "tests.storage.test_txn_limit",
    "tests.test_distributor",
    "tests.test_event_auth",
    "tests.test_federation",
    "tests.test_mau",
    "tests.test_preview",
    "tests.test_test_utils",
    "tests.test_types",
    "tests.test_utils",
    "tests.test_utils.event_injection",
    "tests.test_utils.html_parsers",
    "tests.test_utils.logging_setup",
    "tests.util.test_glob_to_regex",
    "tests.util.test_itertools",
    "tests.util.test_logformatter",
    "tests.util.test_ratelimitutils",
    "tests.util.test_retryutils",
    "tests.util.test_stream_change_cache",
    "tests.util.test_stringutils",
    "tests.util.test_threepids",
    "tests.util.test_treecache",
    "txredisapi",
]
allow_untyped_defs = true

# Dependencies without annotations
# Before ignoring a module, check to see if type stubs are available.
# The `typeshed` project maintains stubs here:
#     https://github.com/python/typeshed/tree/master/stubs
# and for each package `foo` there's a corresponding `types-foo` package on PyPI,
# which we can pull in as a dev dependency by adding to `setup.py`'s
# `CONDITIONAL_REQUIREMENTS["mypy"]` list.
[[tool.mypy.overrides]]
module = [
    "authlib.*",
    "bcrypt",
    "canonicaljson",
    "constantly",
    "daemonize",
    "h11",
    "hiredis",
    "hyperlink",
    "ijson.*",
    "jaeger_client.*",
    "josepy.*",
    "jwt.*",
    "lxml",
    "msgpack",
    "nacl.*",
    "netaddr",
    "opentracing",
    "parameterized.*",
    "phonenumbers.*",
    "prometheus_client.*",
    "pymacaroons.*",
    "pympler.*",
    "rust_python_jaeger_reporter.*",
    "saml2.*",
    "sentry_sdk",
    "service_identity.*",
    "signedjson.*",
    "treq.*",
    "twisted.*",
    "zope",
]
ignore_missing_imports = true
