---
apiVersion: apps/v1 
#extensions/v1beta1
kind: Deployment
metadata:
  annotations:
#    fabric8.io/git-commit: 9835f5100a549e30a10dd1303b0952234aea14b9
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=pegacorn-communicate-roomserver&var-version=1.0.0-SNAPSHOT
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/fhirbox/pegacorn-communicate-roomserver
  labels:
    app: {{ .Values.serviceName }}
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: net.fhirbox.pegacorn
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
      provider: fabric8
      group: net.fhirbox.pegacorn
  template:
    metadata:
      annotations:
#        fabric8.io/git-commit: 9835f5100a549e30a10dd1303b0952234aea14b9
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=pegacorn-communicate-roomserver&var-version=1.0.0-SNAPSHOT
        fabric8.io/iconUrl: img/icons/camel.svg
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
      labels:
        app: {{ .Values.serviceName }}
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: net.fhirbox.pegacorn
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      {{ if (.Values.acrSecretName) }} 
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{ end }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: computeResources
                operator: In
                values:
                - High
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JVM_MAX_HEAP_SIZE
          value: "1536m"
        resources:
          limits:
            memory: "2048Mi"
        image: {{ .Values.dockerRepo }}pegacorn/pegacorn-communicate-roomserver:{{ .Values.imageTag }}            
        imagePullPolicy: IfNotPresent
        name: synapes
        ports:
        - containerPort: 8448
          name: https
          protocol: TCP
        securityContext:
          privileged: false
        volumeMounts:
        - name: data
          mountPath: /var/lib/synapse/data
        - name: config
          mountPath: /var/lib/synapse/config
        - name: certificates
          mountPath: /var/lib/synapse/certificates
      volumes:
      - name: data
        hostPath: 
          path: {{ .Values.hostPath }}/data
      - name: config
        hostPath: 
          path: {{ .Values.hostPath }}/config
      - name: certificates
        hostPath:
          path: {{ .Values.hostPathCerts }}