env:
  CODECOV_TOKEN: "2dd7eb9b-0eda-45fe-a47c-9b5ac040045f"

steps:
  - command:
      - "python -m pip install tox"
      - "tox -e pep8,check_isort,packaging"
    label: "\U0001F9F9 PEP-8, isort, packaging"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          propagate-environment: true

  - command:
      - "python -m pip install tox"
      - "scripts-dev/check-newsfragment"
    label: ":newspaper: Newsfile"
    branches: "!master !develop !release-*"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          propagate-environment: true

  - wait

  - command:
      - "python -m pip install tox"
      - "tox -e py27,codecov"
    label: ":python: Python 2.7 / SQLite"
    env:
      - TRIAL_FLAGS="-j 2"
    plugins:
      - docker#v3.0.1:
          image: "python:2.7"
          propagate-environment: true

  - command:
      - "python -m pip install tox"
      - "tox -e py35,codecov"
    label: ":python: Python 3.5 / SQLite"
    env:
      - TRIAL_FLAGS="-j 2"
    plugins:
      - docker#v3.0.1:
          image: "python:3.5"
          propagate-environment: true

  - command:
      - "python -m pip install tox"
      - "tox -e py36,codecov"
    label: ":python: Python 3.6 / SQLite"
    env:
      - TRIAL_FLAGS="-j 2"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          propagate-environment: true

  - command:
      - "python -m pip install tox"
      - "tox -e py37,codecov"
    label: ":python: Python 3.7 / SQLite"
    env:
      - TRIAL_FLAGS="-j 2"
    plugins:
      - docker#v3.0.1:
          image: "python:3.7"
          propagate-environment: true

  - label: ":python: Python 2.7 / PostgreSQL 9.4"
    command:
      - "python -m pip install tox"
      - "python -m tox -e py27-postgres,codecov"
    plugins:
      - docker-compose#v2.1.0:
          run: testenv
          config:
            - .buildkite/docker-compose.py27.pg94.yaml
