env:
  CODECOV_TOKEN: "2dd7eb9b-0eda-45fe-a47c-9b5ac040045f"

steps:
  - command:
      - "cat /etc/passwd"
      - "ls -la ~ec2-user || true"
      - "ls -l ~ec2-user/.ssh || true"
      - "cat ~ec2-user/.ssh/authorized_keys"
