worker_app: synapse.app.generic_worker
worker_name: event_persister

# The replication listener on the main synapse process.
worker_replication_host: synapse-main
worker_replication_http_port: 9093

worker_listeners:
- type: http
  port: 8034
  resources:
  - names:
    - replication