name: matrix-synapse
base: core18
version: git 
summary: Reference Matrix homeserver
description: |
  Synapse is the reference Matrix homeserver.
  Matrix is a federated and decentralised instant messaging and VoIP system.

grade: stable 
confinement: strict 

apps:
  matrix-synapse: 
    command: synctl --no-daemonize start $SNAP_COMMON/homeserver.yaml
    stop-command: synctl -c $SNAP_COMMON stop
    plugs: [network-bind, network]
    daemon: simple 
parts:
  matrix-synapse:
    source: .
    plugin: python
    python-version: python3
