name: Complement Tests

on:
#  push:
#    branches: ["develop", "release-*"]
#  pull_request:
#  schedule:
# eg. runs everyday at 4am    - 0 4 * * *
# eg. runs every sundat at 4am  - 0 4 * * 0

# Note: this will only work if this test exists on default branch, which is 'develop'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  calculate-test-jobs:
    name: "Calculate Test Jobs"
    if: ${{ !cancelled() && !failure() }} # Allow previous steps to be skipped, but not fail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - id: get-matrix
        run: .ci/scripts/calculate_jobs.py
    outputs:
      complement_singles_test_matrix: ${{ steps.get-matrix.outputs.complement_singles_test_matrix }}
      complement_sharding_test_matrix: ${{ steps.get-matrix.outputs.complement_sharding_test_matrix }}
      complement_stream_writers_test_matrix: ${{ steps.get-matrix.outputs.complement_stream_writers_test_matrix }}

  singles:
    name: Singles
    if: "${{ !failure() && !cancelled() }}"
    needs: calculate-test-jobs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_singles_test_matrix) }}

    steps:
      - name: Run actions/checkout@v3 for synapse
        uses: actions/checkout@v3
        with:
          path: synapse

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.58.1
            override: true
      - uses: Swatinem/rust-cache@v2

      - name: Prepare Complement's Prerequisites
        run: synapse/.ci/scripts/setup_complement_prerequisites.sh

      - name: Run Complement Tests
        shell: bash
        env:
          POSTGRES: "true"
          WORKERS: "true"
          SYNAPSE_WORKER_TYPES: ${{ matrix.job.worker_types }}
        run: |
          set -o pipefail
          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement.sh -json 2>&1 | synapse/.ci/scripts/gotestfmt


  # a job which marks all the other jobs as complete, thus allowing PRs to be merged.
  tests-done:
    name: Tests Done
    if: ${{ always() }}
    needs:
      - singles
    runs-on: ubuntu-latest
    steps:
      - uses: matrix-org/done-action@v2
        with:
          needs: ${{ toJSON(needs) }}

          # skippable:
