name: Write changelog for dependabot PR
on:
  pull_request:
    types:
      - opened
      - synchronize  # dmr test

jobs:
  add-changelog:
    runs-on: 'ubuntu-latest'
    if: github.actor == 'dependabot[bot]' || github.actor == 'dmrobertson'  # DMR TEST
    steps:
      - uses: actions/checkout@v3
      - name: Write, commit and push changelog
        run: |
          echo "${{ github.pull_request.title }}" > "changelog.d/${{ github.pull_request.number }}".docker
          git add changelog.d
          git commit -m "Changelog"
          git push
        env:
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
        shell: bash
