name: Move labelled issues to correct projects

on:
  issues:
    types: [ labeled ]

jobs:
  move_needs_info:
    name: Move X-Needs-Info on the triage board
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'X-Needs-Info')
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $projectid
                  itemId: $contentid
                  fieldId: $fieldid
                  value: {
                    singleSelectOptionId: "Todo"
                  }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }

          projectid: ${{ env.PROJECT_ID }}
          contentid: ${{ github.event.issue.node_id }}
          fieldid: ${{ env.FIELD_ID }}
          optionid: ${{ env.OPTION_ID }}
        env:
          PROJECT_ID: "PVT_kwDOAIB0Bs4AFDdZ"
          GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
          FIELD_ID: "PVTSSF_lADOAIB0Bs4AFDdZzgC6ZA4"
          OPTION_ID: "ba22e43c"
